name: MischiefAutoBroadcast
version: 0.0.7
author: sven@wollinger.email
main: com.mischiefsmp.autobroadcast.MischiefAutoBroadcast
api-version: 1.18
softdepend: ["MischiefCore"]
commands:
  autobroadcast:
    description: Main plugin command
    usage: /<command>